modLoader = "javafml"
loaderVersion = "[2,)"
license = "MIT"

[[mods]]
modId = "defaulted_hotkeys"
displayName = "Defaulted Hotkeys"
version = "${version}"
logoFile = "logo.png"
authors = "IAFEnvoy"
description = '''Change any default keybindings.'''

[[dependencies.defaulted_hotkeys]]
modId = "forge"
mandatory = true
versionRange = "[1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.defaulted_hotkeys]]
modId = "minecraft"
mandatory = true
versionRange = "[0,)"

[[mixins]]
config = "defaulted_hotkeys.mixins.json"
