modLoader = "javafml"
loaderVersion = "[2,)"
license = "MIT"

[[mods]]
modId = "defaulted_hotkeys"
displayName = "Defaulted Hotkeys"
version = "${version}"
logoFile = "logo.png"
authors = "IAFEnvoy"
description = '''Change any default keybindings.'''

[[mixins]]
config = "defaulted_hotkeys.mixins.json"

[[dependencies.defaulted_hotkeys]]
modId = "neoforge"
type = "required"
versionRange = "[1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.defaulted_hotkeys]]
modId = "minecraft"
type = "required"
